apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spooled-example-spriteforge-dev

resources:
  - ../../base

nameSuffix: -dev

labels:
  - includeSelectors: true
    pairs:
      environment: development

patches:
  # Create the correct dev namespace
  - target:
      kind: Namespace
      name: spooled-example-spriteforge
    patch: |-
      - op: replace
        path: /metadata/name
        value: spooled-example-spriteforge-dev
  # Reduce resources for dev
  - target:
      kind: Deployment
      name: spooled-example-spriteforge
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 256Mi
  # Disable public schedule in dev by default
  - target:
      kind: ConfigMap
      name: spooled-example-spriteforge-config
    patch: |-
      - op: replace
        path: /data/ENABLE_PUBLIC_SCHEDULE
        value: "false"
  # Use a separate host for dev
  - target:
      kind: Ingress
      name: spooled-example-spriteforge
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: example-dev.spooled.cloud
      - op: replace
        path: /spec/rules/0/host
        value: example-dev.spooled.cloud
      - op: replace
        path: /spec/tls/0/secretName
        value: spooled-example-spriteforge-dev-tls
