apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spooled-example-spriteforge

resources:
  - ../../base

labels:
  - includeSelectors: true
    pairs:
      environment: production

images:
  - name: ghcr.io/spooled-cloud/spooled-example-spriteforge
    newTag: latest

patches:
  # Ensure we stay at 1 replica (SSE/session routing is simplest that way)
  - target:
      kind: Deployment
      name: spooled-example-spriteforge
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
