apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: spooled-example-spriteforge

namespace: spooled-example-spriteforge

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: spooled-cloud
      app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml

commonLabels:
  app.kubernetes.io/name: spooled-example-spriteforge
  app.kubernetes.io/component: example
  app.kubernetes.io/version: "1.0.15"
